[package]
name = "format"
version = "0.1.0"
authors = ["Mubelotix <mubelotix@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
meilisearch-sdk = {git="https://github.com/meilisearch/meilisearch-rust"}
string-tools = "0.1"